# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/
run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gofmt
    - goimports
    - misspell
    - unconvert
    - goconst
    - bodyclose
    - nilerr
    - errorlint
    - prealloc

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  goimports:
    local-prefixes: github.com/zbb88888/tishi

  errorlint:
    errorf: true
    asserts: true
    comparison: true

issues:
  exclude-rules:
    # Test files are allowed to use dot imports and have longer functions
    - path: _test\.go
      linters:
        - goconst
        - bodyclose
        - errcheck

    # Allow unused parameters in main
    - path: cmd/
      linters:
        - unused

  max-issues-per-linter: 50
  max-same-issues: 10
