# golangci-lint v2 configuration
# https://golangci-lint.run/usage/configuration/
version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/zbb88888/tishi

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - unconvert
    - goconst
    - bodyclose
    - nilerr
    - errorlint

  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow

    goconst:
      min-len: 3
      min-occurrences: 3

    misspell:
      locale: US

    errorlint:
      errorf: true
      asserts: true
      comparison: true

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - goconst
          - bodyclose
          - errcheck

      - path: cmd/
        linters:
          - unused

    max-issues-per-linter: 50
    max-same-issues: 10
